title: Nurture Massage Therapeutic Spa 
email: angela@charlestonscmassage.com 
description: >- # this means to ignore newlines until "baseurl:"
  Nurture Massage Therapeutic Spa in Charleston, SC offers affordable massage and mini-spa services.  Swedish Massage, Dee    p Tissue Massage, Sports Massage, Prenatal/Pregnancy massage, Couples Massage are a few specialties offered...  

# Build settings
markdown: kramdown
theme: minima
baseurl: "/nurture-massage" 
url: "mcmillanator.github.io" 
github_username:  mcmillanator

image_path: 'assets/images/'
